### ISSUE TITLE
README.md: The composer create project and update commands using --no-cache option both fail

### ISSUE THREAD

**Issue by tebb** [localgovdrupal/localgov#145] opened 2020-10-07 22:50 UTC
The README.md file suggests using the create project and update commands with the "--no-cache" option.  These both fail due to this prestissimo issue:

https://github.com/hirak/prestissimo/issues/199

Workaround:

`composer clear cache   # and don't use the "--no-cache" option`

... but that's not ideal.

**Comment by finnlewis** [comment] 2020-10-10 09:52
Hi @tebb 

Thanks for posting the issue. 

What version of composer are you using? 

```
$ composer --version
Composer 1.10.1 2020-03-13 20:34:27

```
On version 1.10 this works for me:
```
composer create-project localgovdrupal/localgov-project MY_PROJECT --stability dev --no-cache
```
I eventually see: 
```
  Congratulations, you’ve installed the LocalGov Drupal codebase  
```

**Comment by tebb** [comment] 2020-10-10 13:22
Hi Finn,

Perhaps I should stick to driving lorries? ;)

This isn't a problem to me, I just wanted to avoid evaluators having problems.  I just want to work on a simple issue from the queue.

I have Composer version: 1.10.13, so I downgraded to 1.10.1, ran composer clear-cache and then your command:

composer create-project localgovdrupal/localgov-project MY_PROJECT --stability dev --no-cache

=> Still encountered the same issue.

For my needs I can use the workaround of clearing the cache and omitting the --no-cache option, but 'just in cases', out of interest, I tried composer 2.0.0 rc1.  That reported issues with plugins, so I've switched back to 1.10.13.

I'm on Ubuntu 20.04, PHP7.4.3.

If you can suggest anything else, I'll try that, but as I said, personally I don't need this resolved.

Tebb ;)

**Comment by finnlewis** [comment] 2020-10-11 16:45
I've also tested with the latest composer and cannot reproduce an error:

```
finn@finnibuntu:~/sites/l.localgov/MY_PROJECT$ composer --version
Composer version 1.10.13 2020-09-09 11:46:34

```

For the record, this is the error that @tebb sees: 
```

  [ErrorException]
  mkdir(): Not a directory  
```
Closing this as cannot reproduce.

**Closed by finnlewis** 2020-10-11 16:45 UTC

**Comment by tebb** [comment] 2020-10-11 18:53
Updates:

1) The install works for me if run under sudo as follows:

sudo composer create-project localgovdrupal/localgov-project MY_PROJECT --stability dev --no-cache

Conclusion: sudo allows prestissimo to create temporary files it needs, even though composer doesn't use a cache.

2) There is a proposed fix, pull request for this issue for hirak/prestissimo

https://github.com/hirak/prestissimo/pull/214/commits/9673bc28e8bcb6905184e28452bd91615c9de555

3) I installed prestissimo globally, then applied the patch from 2), then ran the following, with --no-cache, but without sudo.

composer create-project localgovdrupal/localgov-project MY_PROJECT --stability dev --no-cache

As I hit return, I thought "Ah ... this isn't going to work, because it will ignore the locally installed patched prestissimo".

... but it created the project successfully.

Conclusion: Even with --no-cache, composer uses local, globally installed packages.
